<?php

return [
    'create' => <<<SQL
        id VARCHAR(500) PRIMARY KEY,
        limit_usertest INT(100) NOT NULL,
        roll_Status BOOL NOT NULL,
        username VARCHAR(500) NOT NULL,
        Processing_value TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
        Processing_value_one TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
        Processing_value_tow TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
        Processing_value_four TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
        step VARCHAR(500) NOT NULL,
        description_blocking TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
        number VARCHAR(300) NOT NULL,
        Balance INT(255) NOT NULL,
        User_Status VARCHAR(500) NOT NULL,
        pagenumber INT(10) NOT NULL,
        message_count VARCHAR(100) NOT NULL,
        last_message_time VARCHAR(100) NOT NULL,
        agent VARCHAR(100) NOT NULL,
        affiliatescount VARCHAR(100) NOT NULL,
        affiliates VARCHAR(100) NOT NULL,
        namecustom VARCHAR(300) NOT NULL,
        number_username VARCHAR(300) NOT NULL,
        register VARCHAR(100) NOT NULL,
        verify VARCHAR(100) NOT NULL,
        cardpayment VARCHAR(100) NOT NULL,
        codeInvitation VARCHAR(100) NULL,
        pricediscount VARCHAR(100) NULL DEFAULT '0',
        hide_mini_app_instruction VARCHAR(20) NULL DEFAULT '0',
        maxbuyagent VARCHAR(100) NULL DEFAULT '0',
        joinchannel VARCHAR(100) NULL DEFAULT '0',
        checkstatus VARCHAR(50) NULL DEFAULT '0',
        bottype TEXT NULL,
        score INT(255) NULL DEFAULT '0',
        limitchangeloc VARCHAR(50) NULL DEFAULT '0',
        status_cron VARCHAR(20) NULL DEFAULT '1',
        expire VARCHAR(100) NULL,
        token VARCHAR(100) NULL,
        lang VARCHAR(5) NULL DEFAULT 'fa'
        SQL,
    'columns' => [
        ['username', 'none'],
        ['Processing_value', 'none'],
        ['Processing_value_four', ''],
        ['number', 'none'],
        ['pagenumber', ''],
        ['message_count', '0'],
        ['last_message_time', '0'],
        ['agent', 'f'],
        ['affiliatescount', '0'],
        ['affiliates', '0'],
        ['namecustom', 'none'],
        ['number_username', '100'],
        ['register', 'none'],
        ['verify', '1'],
        ['cardpayment', '1'],
        ['codeInvitation', null],
        ['pricediscount', '0'],
        ['hide_mini_app_instruction', '0', 'VARCHAR(20)'],
        ['maxbuyagent', '0'],
        ['joinchannel', '0', 'VARCHAR(100)'],
        ['checkstatus', '0', 'VARCHAR(50)'],
        ['bottype', '0', 'TEXT'],
        ['score', '0', 'INT(255)'],
        ['limitchangeloc', '0', 'VARCHAR(50)'],
        ['status_cron', '1', 'VARCHAR(20)'],
        ['expire', null, 'VARCHAR(100)'],
        ['token', null, 'VARCHAR(100)'],
        ['lang', 'fa', 'varchar(5)'],
    ],
];
